### ISSUE TITLE
I had to change the Server.ts file 

### ISSUE THREAD

**Issue by jaypolanco96** [Dirk94/express-react-app#1]
my react build went inside of the frontend folder so i had to change the Server.ts into 

```
import {Express, Request, Response} from "express";
import express from "express";
import * as path from "path";

export class Server {

    private app: Express;

    constructor(app: Express) {
        this.app = app;

        this.app.use(express.static(path.resolve("./") + "/frontend/build/"));

        this.app.get("/api", (req: Request, res: Response): void => {
            res.send("You have reached the API!");
        });

        this.app.get("*", (req: Request, res: Response): void => {
            res.sendFile(path.resolve("./") + "/frontend/build/index.html");
        });
    }

    public start(port: number): void {
        this.app.listen(port, () => console.log(`Server listening on port ${port}!`));
    }

}

```

**Comment by Dirk94** [comment]
Personally I prefer to keep the builds of both the frontend and backend in the same build folder.

That is why I changed the `frontend/package.json` build script to move the build one level up:
```"build": "react-scripts build && mv ./build ../build/frontend"```

So the frontend build should end up in the `build/frontend` folder. Let me know if this doesn't work for you!

**Comment by jaypolanco96** [comment]
ohhhh now I remember that i saw an error in Visual Studio Code that said "could not move build folder" and I didn't understand what it meant. The problem might be a _sudo_ permissions problem in my terminal. Im going to close this issue. Sorry and blessings to you! Awesome SSR, I love it ! Blessings !
